import { useEffect, useState, type Dispatch, type SetStateAction } from "react"
import type { MonitorAuthenticationPayload, MonitorAuthenticationType } from "@/types/monitor-authentication/monitor-authentication.types"

export function MonitorAuthenticationForm({ value, onChange, requireSecrets = true }: { value: MonitorAuthenticationPayload; onChange: Dispatch<SetStateAction<MonitorAuthenticationPayload>>; requireSecrets?: boolean }) {
  const [loginBodyText, setLoginBodyText] = useState(JSON.stringify(value.credentials.loginBody || {}, null, 2))
  useEffect(() => { setLoginBodyText(JSON.stringify(value.credentials.loginBody || {}, null, 2)) }, [value.authType])
  const update = (patch: Partial<MonitorAuthenticationPayload>) => onChange({ ...value, ...patch })
  const credentials = value.credentials
  return <div className="authentication-fields"><label>Authentication<select value={value.authType} onChange={(event) => update({ authType: event.target.value as MonitorAuthenticationType })}><option value="none">No authentication</option><option value="api_key">API key</option><option value="bearer_token">Bearer token</option><option value="basic">Basic auth</option><option value="dynamic_login">Login endpoint</option></select></label>{value.authType === "api_key" && <><label>Header name<input required value={credentials.headerName || "X-API-Key"} onChange={(event) => update({ credentials: { ...credentials, headerName: event.target.value } })} /></label><label>API key<input required={requireSecrets} type="password" value={credentials.apiKey || ""} onChange={(event) => update({ credentials: { ...credentials, apiKey: event.target.value } })} /></label></>}{value.authType === "bearer_token" && <label>Bearer token<input required={requireSecrets} type="password" value={credentials.token || ""} onChange={(event) => update({ credentials: { ...credentials, token: event.target.value } })} /></label>}{value.authType === "basic" && <div className="form-row"><label>Username<input required={requireSecrets} value={credentials.username || ""} onChange={(event) => update({ credentials: { ...credentials, username: event.target.value } })} /></label><label>Password<input required={requireSecrets} type="password" value={credentials.password || ""} onChange={(event) => update({ credentials: { ...credentials, password: event.target.value } })} /></label></div>}{value.authType === "dynamic_login" && <><label>Login URL<input required type="url" value={value.loginUrl || ""} onChange={(event) => update({ loginUrl: event.target.value })} placeholder="https://api.example.com/login" /></label><div className="form-row"><label>Login body type<select value={value.loginBodyType || "json"} onChange={(event) => update({ loginBodyType: event.target.value as "json" | "form_urlencoded" | "multipart" })}><option value="json">JSON</option><option value="form_urlencoded">Form URL encoded</option><option value="multipart">Multipart form data</option></select></label><label>Token JSON path<input required value={value.tokenJsonPath || "data.accessToken"} onChange={(event) => update({ tokenJsonPath: event.target.value })} /></label></div><label>Expires in path<input value={value.expiresInJsonPath || ""} onChange={(event) => update({ expiresInJsonPath: event.target.value })} placeholder="data.expiresIn" /></label><label>Login body<textarea required={requireSecrets} value={loginBodyText} onChange={(event) => { setLoginBodyText(event.target.value); try { update({ credentials: { ...credentials, loginBody: JSON.parse(event.target.value) } }) } catch { /* wait for valid JSON */ } }} /></label></>}</div>
}
